### ISSUE TITLE
ImportError: cannot import name 'get_cell_based_tiny_net' from 'models' (unknown location)

### ISSUE THREAD

**Issue by Mhrooz** [rohanasthana/DiNAS#1]
Hi, I tried to deploy the DiNAS but I got this error message:

```
Traceback (most recent call last):                                                                                    
 File "/home/DiNAS/main_reg_free.py", line 25, in <module>
    from src.datasets.nasbench301dataset_reg_free import NASBench301Dataset,NASBench301DatasetInfos, NASBench301DataModule
  File "/home/DiNAS/src/datasets/nasbench301dataset_reg_free.py", line 15, in <module>
    from src.NASBench301_self import Dataset                                                                          
 File "/home/DiNAS/src/NASBench301_self.py", line 114, in <module>
    from src.procedures_darts import TENAS                                                                             
File "/home/src/procedures_darts.py", line 25, in <module>
    from models import get_cell_based_tiny_net, get_search_spaces
ImportError: cannot import name 'get_cell_based_tiny_net' from 'models' (unknown location)
```

It found that the `src/models/__init__.py` file in github repository is an empty file. Maybe you forgot to upload the code there?

btw, the Google Drive link is in the readme.md is invalid as well. Could you please update the link?

Thanks for your help in advance: )

**Comment by rohanasthana** [comment]
Hi,
Thank you for the raised issue. The procedure darts import is not necessary in the file and was thus removed. The drive link in the readme file was also updated as per the request.
