### ISSUE TITLE
ModuleNotFoundError: No module named 'src.datasets.nasbench.lib'

### ISSUE THREAD

**Issue by sustech-lz** [rohanasthana/DiNAS#2]
python main_reg_free.py --dataset nasbench101
<frozen importlib._bootstrap>:228: RuntimeWarning: to-Python converter for std::vector<int, std::allocator<int> > already registered; second conversion method ignored.
<frozen importlib._bootstrap>:228: RuntimeWarning: to-Python converter for std::vector<double, std::allocator<double> > already registered; second conversion method ignored.
<frozen importlib._bootstrap>:228: RuntimeWarning: to-Python converter for std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > already registered; second conversion method ignored.
<frozen importlib._bootstrap>:228: RuntimeWarning: to-Python converter for std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > > already registered; second conversion method ignored.
<frozen importlib._bootstrap>:228: RuntimeWarning: to-Python converter for boost::python::detail::container_element<std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, unsigned long, boost::python::detail::final_vector_derived_policies<std::vector<std::vector<double, std::allocator<double> >, std::allocator<std::vector<double, std::allocator<double> > > >, false> > already registered; second conversion method ignored.
2024-09-14 22:25:25.665566: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-14 22:25:26.240624: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Found rdkit, all good
Traceback (most recent call last):
  File "/home/lz/DiNAS/main_reg_free.py", line 26, in <module>
    from src.datasets.nasbenchNLPdataset_reg_free import NASBenchNLPDataset,NASBenchNLPDatasetInfos, NASBenchNLPDataModule
  File "/home/lz/DiNAS/src/datasets/nasbenchNLPdataset_reg_free.py", line 15, in <module>
    from src.NASBenchNLP_self import Dataset
  File "/home/lz/DiNAS/src/NASBenchNLP_self.py", line 45, in <module>
    from src.nasbenchx11.nas_bench_x11.api import load_ensemble
  File "/home/lz/DiNAS/src/nasbenchx11/nas_bench_x11/api.py", line 17, in <module>
    from nas_bench_x11.ensemble import Ensemble
  File "/home/lz/DiNAS/src/nasbenchx11/nas_bench_x11/ensemble.py", line 13, in <module>
    from nas_bench_x11.utils import utils
  File "/home/lz/DiNAS/src/nasbenchx11/nas_bench_x11/utils/utils.py", line 23, in <module>
    from nas_bench_x11.models.lgboost import LGBModel, LGBModelTime
  File "/home/lz/DiNAS/src/nasbenchx11/nas_bench_x11/models/lgboost.py", line 14, in <module>
    from nas_bench_x11.surrogate_model import SurrogateModel
  File "/home/lz/DiNAS/src/nasbenchx11/nas_bench_x11/surrogate_model.py", line 13, in <module>
    from nas_bench_x11.encodings.encoding import encode
  File "/home/lz/DiNAS/src/nasbenchx11/nas_bench_x11/encodings/encoding.py", line 3, in <module>
    from nas_bench_x11.encodings.encodings_nb101 import encode_nb101
  File "/home/lz/DiNAS/src/nasbenchx11/nas_bench_x11/encodings/encodings_nb101.py", line 2, in <module>
    from src.datasets.nasbench import api
  File "/home/lz/DiNAS/src/datasets/nasbench/api.py", line 97, in <module>
    from src.datasets.nasbench.lib import config
ModuleNotFoundError: No module named 'src.datasets.nasbench.lib'

**Comment by wenxe1** [comment]
hello，do you solve this problem?

**Comment by rohanasthana** [comment]
Please check if src.datasets.nasbench.lib exists. If not, then it must be because the root directory is different. In that case, try removing the "src" from the import
